Documentation and module file modified
teamviewer/TeamViewerPS pull request #52
Opened 2023-10-08 23:22 UTC by karthickgandhiTV

about_TeamViewerPS.md -> TeamViewerPS.md
TeamViewerPS.psm1 file update

2023-10-09 17:28 UTC, ChristianJ-TV requested changes

2023-10-09 17:28 UTC, ChristianJ-TV commented on README.md
> +Please see the [TeamViewerPS](docs/aTeamViewerPS.md) article for a more detailed list.
"docs/aTeamViewerPS.md"  -> "docs/TeamViewerPS.md"

2023-10-10 02:26 UTC, karthickgandhiTV commented on README.md
> +Please see the [TeamViewerPS](docs/aTeamViewerPS.md) article for a more detailed list.
Fixed 👍

2023-10-12 14:05 UTC, ChristianJ-TV approved these changes

2023-10-12 14:05 UTC, merged