Harmonize cmdlet names
teamviewer/TeamViewerPS pull request #61
Opened 2023-10-20 18:39 UTC by ChristianJ-TV

- Renames user role to role
- Harmonizes cmdlet names

2023-10-21 08:01 UTC, karthickgandhiTV commented on Cmdlets/Private/ConvertTo-TeamViewerPredefinedRole.ps1
PredefinedRoleId = $InputObject.PredefineduserRoleId

This should be $InputObject.PredefineduserRoleId since this is the response we receive from API

2023-10-21 08:35 UTC, karthickgandhiTV requested changes

2023-10-21 08:35 UTC, karthickgandhiTV commented on Cmdlets/Public/Add-TeamViewerUserToRole.ps1
Variables inside body should remain unchanged since it is a payload for the PUT request

2023-10-21 08:35 UTC, karthickgandhiTV commented on Cmdlets/Public/Remove-TeamViewerUserFromRole.ps1
> +            RoleId  = $id
RoleId -> UserRoleId since it is a payload

2023-10-21 08:35 UTC, karthickgandhiTV commented on Cmdlets/Public/Set-TeamViewerRole.ps1
> +            RoleId      = $RoleId
RoleId -> UserRoleId since it is a payload

2023-10-21 11:12 UTC, ChristianJ-TV commented
Thanks for the review, @karthickgandhiTV, all requests changes were made and tests fixed.

2023-10-22 12:29 UTC, karthickgandhiTV commented on Cmdlets/Public/Add-TeamViewerUserGroupToRole.ps1
> +            RoleId      = $RoleId
![image](https://github.com/teamviewer/TeamViewerPS/assets/139859343/14374760-400b-463c-8e29-d92d8c5d1226)

RoleId -> UserRoleId

2023-10-22 12:30 UTC, karthickgandhiTV approved these changes

2023-10-22 13:13 UTC, ChristianJ-TV commented on Cmdlets/Public/Add-TeamViewerUserGroupToRole.ps1
> +            RoleId      = $RoleId
Thanks, didn't see it after too many search & replace actions.

2023-10-22 13:16 UTC, merged